### ISSUE TITLE
Protokoll für Kommunikation

### ISSUE THREAD

**Issue by tm07** [shatoboar/EES#7]
Protokoll zur Kommunikation zwischen Raspberry und NXT spezifizieren.

**Comment by filiprejmus** [comment]
Implement protocols according to the specification presented in milestone 2

**Comment by filiprejmus** [comment]
Subtasks TODO List:

- [ ] Specify and Implement Buffer structure for different sends
- [ ] Implement Acks and Checksums (are checksums already part of the BT protocols?)
- [ ] Expose communication to C++/NXT via functions
- [ ] (Filip) Create cmakefile

**Comment by filiprejmus** [comment]
Specification of Messages
Message length: 4; 
2 preceeding bytes (?), 2 payload bytes; 
first payload byte: message type,
second: message content

message type:
255 : Resend request - _None_
1: Acknowledgements - _None_
2: Init (#buckets) - _PI -> NXT none; NXT -> PI #buckets_
3: Deploy new item Signal -_None_
4: Predicted Bucketnumber - _PI -> NXT bucket index prediction; NXT -> PI  None_
